server:
  port: 0

spring:
  application:
    name: statistics
  jpa:
    database:
    show-sql: true
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5433/client_db
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  second-datasource:
    jdbcUrl: jdbc:postgresql://localhost:5433/gpus_db
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
sender:
  url: http://localhost:8765/sender